language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - mkdir -p /tmp/bin
  - ./tests/build_etcd.sh v2.2.5
  - ./tests/build_uq.sh
  - cp ./tests/wait_etcd.sh /tmp/bin
  - cp ./tests/start_servers.sh /tmp/bin
install:
  - pip install coveralls
before_script:
  - export PATH=$PATH:/tmp/bin
  - start_servers.sh
  - cd ${TRAVIS_BUILD_DIR}
script:
  coverage run --source=uq setup.py test
after_success:
  coveralls
env: TRAVIS=True
